import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, List, Dict, Any
from dotenv import load_dotenv

from utils.logger import get_logger

logger = get_logger("config")

# Project root determined dynamically (100% relative path resolution)
BASE_DIR = Path(__file__).resolve().parent.parent

# Standardized relative paths
ENV_FILE = BASE_DIR / ".env"
LOGS_DIR = BASE_DIR / "logs"
AI_CONTEXT_DIR = BASE_DIR / ".ai-context"
TICKETS_DIR = AI_CONTEXT_DIR / "tickets"
INDEX_FILE = AI_CONTEXT_DIR / "INDEX.md"
CATALOG_FILE = AI_CONTEXT_DIR / "catalog.json"

# Project Permission Scheme Keys (Internal Jira Permissions)
REQUIRED_PERMISSIONS: List[Dict[str, str]] = [
    {
        "key": "BROWSE_PROJECTS",
        "name": "Browse Projects",
        "desc": "Ability to browse projects, search issues, and view ticket details.",
    },
]

# Atlassian REST API v3 Granular Scopes (OAuth 2.0 / App Scopes standard)
JIRA_GRANULAR_SCOPES: List[Dict[str, str]] = [
    {"scope": "read:me", "desc": "Access user profile and verify authentication (GET /rest/api/3/myself)"},
    {"scope": "read:jira-work", "desc": "Read Jira project and issue metadata (classic scope covering all issue reads)"},
    {"scope": "read:issue-details:jira", "desc": "Read ticket description, summary, fields, and links"},
    {"scope": "read:attachment:jira", "desc": "View and download attached screenshots and image assets"},
    {"scope": "read:issue.changelog:jira", "desc": "Read ticket requirement change history (NOT read:audit-log:jira)"},
]


@dataclass
class JiraConfig:
    base_url: str
    email: str
    api_token: str
    max_asset_size_mb: int = 15

    @property
    def is_configured(self) -> bool:
        return bool(self.base_url and self.email and self.api_token)

    @property
    def clean_base_url(self) -> str:
        return self.base_url.rstrip("/") if self.base_url else ""


def load_config() -> JiraConfig:
    """Loads Jira configuration with priority:
    1. Process Environment Variables (injected dynamically by Master MCP)
    2. Central JSON Secrets file (via CENTRAL_CONFIG_PATH)
    3. Local .env file (standalone CLI fallback)
    """
    # Load .env without overriding already-injected process variables
    if ENV_FILE.exists():
        load_dotenv(dotenv_path=ENV_FILE, override=False)
        logger.debug(f"Loaded local fallback configuration from {ENV_FILE}")

    # Support central tokens file if configured by Master MCP
    central_path_str = os.getenv("CENTRAL_CONFIG_PATH", "")
    central_jira: Dict[str, Any] = {}
    if central_path_str:
        central_path = Path(central_path_str).expanduser().resolve()
        if central_path.exists():
            try:
                import json
                parsed = json.loads(central_path.read_text(encoding="utf-8"))
                if isinstance(parsed, dict):
                    central_jira = parsed.get("jira", parsed)
                logger.debug(f"Loaded central tokens from {central_path}")
            except Exception as e:
                logger.warning(f"Could not parse central config at {central_path}: {e}")

    base_url = (os.getenv("JIRA_BASE_URL") or central_jira.get("base_url") or "").strip()
    email = (os.getenv("JIRA_EMAIL") or central_jira.get("email") or "").strip()
    api_token = (os.getenv("JIRA_API_TOKEN") or central_jira.get("api_token") or "").strip()

    try:
        max_size = int(os.getenv("MAX_ASSET_SIZE_MB") or central_jira.get("max_asset_size_mb", 15))
    except ValueError:
        max_size = 15

    return JiraConfig(
        base_url=base_url,
        email=email,
        api_token=api_token,
        max_asset_size_mb=max_size,
    )


def save_config(base_url: str, email: str, api_token: str, max_asset_size_mb: int = 15) -> None:
    """Persists credentials and settings safely into local .env file."""
    base_url = base_url.strip().rstrip("/")
    email = email.strip()
    api_token = api_token.strip()

    content = (
        f"# Jira Cloud Configuration (Auto-generated by CLI)\n"
        f"JIRA_BASE_URL={base_url}\n"
        f"JIRA_EMAIL={email}\n"
        f"JIRA_API_TOKEN={api_token}\n\n"
        f"# Asset Download Limits\n"
        f"MAX_ASSET_SIZE_MB={max_asset_size_mb}\n"
    )

    try:
        ENV_FILE.write_text(content, encoding="utf-8")
        logger.info(f"Configuration saved successfully to {ENV_FILE}")
    except Exception as e:
        logger.error(f"Failed to write configuration to {ENV_FILE}: {e}", exc_info=True)
        raise
